package = "smw-tas"
version = "dev-1"
source = {
   url = "git+ssh://git@github.com/rodamaral/smw-tas.git"
}
description = {
   summary = "![smw-tas for lsnes screenshot](http://i.imgur.com/YpnrF1C.png)",
   detailed = "![smw-tas for lsnes screenshot](http://i.imgur.com/YpnrF1C.png)",
   homepage = "*** please enter a project homepage ***",
   license = "*** please specify a license ***"
}
dependencies = {
    "argparse >= 0.7.0"
}
build = {
   type = "builtin",
   modules = {
      ["lsnes.scripts.lib.cheat"] = "lsnes/scripts/lib/cheat.lua",
      ["lsnes.scripts.lib.commands"] = "lsnes/scripts/lib/commands.lua",
      ["lsnes.scripts.lib.config"] = "lsnes/scripts/lib/config.lua",
      ["lsnes.scripts.lib.display"] = "lsnes/scripts/lib/display.lua",
      ["lsnes.scripts.lib.draw"] = "lsnes/scripts/lib/draw.lua",
      ["lsnes.scripts.lib.game.blockdup"] = "lsnes/scripts/lib/game/blockdup.lua",
      ["lsnes.scripts.lib.game.collision"] = "lsnes/scripts/lib/game/collision.lua",
      ["lsnes.scripts.lib.game.controller"] = "lsnes/scripts/lib/game/controller.lua",
      ["lsnes.scripts.lib.game.countdown"] = "lsnes/scripts/lib/game/countdown.lua",
      ["lsnes.scripts.lib.game.gamemode"] = "lsnes/scripts/lib/game/gamemode.lua",
      ["lsnes.scripts.lib.game.image"] = "lsnes/scripts/lib/game/image.lua",
      ["lsnes.scripts.lib.game.limits"] = "lsnes/scripts/lib/game/limits.lua",
      ["lsnes.scripts.lib.game.map16"] = "lsnes/scripts/lib/game/map16.lua",
      ["lsnes.scripts.lib.game.misc"] = "lsnes/scripts/lib/game/misc.lua",
      ["lsnes.scripts.lib.game.player"] = "lsnes/scripts/lib/game/player.lua",
      ["lsnes.scripts.lib.game.registeraddress"] = "lsnes/scripts/lib/game/registeraddress.lua",
      ["lsnes.scripts.lib.game.rng"] = "lsnes/scripts/lib/game/rng.lua",
      ["lsnes.scripts.lib.game.smw"] = "lsnes/scripts/lib/game/smw.lua",
      ["lsnes.scripts.lib.game.smwdebug"] = "lsnes/scripts/lib/game/smwdebug.lua",
      ["lsnes.scripts.lib.game.sprites.bounce"] = "lsnes/scripts/lib/game/sprites/bounce.lua",
      ["lsnes.scripts.lib.game.sprites.cluster"] = "lsnes/scripts/lib/game/sprites/cluster.lua",
      ["lsnes.scripts.lib.game.sprites.coin"] = "lsnes/scripts/lib/game/sprites/coin.lua",
      ["lsnes.scripts.lib.game.sprites.extended"] = "lsnes/scripts/lib/game/sprites/extended.lua",
      ["lsnes.scripts.lib.game.sprites.generator"] = "lsnes/scripts/lib/game/sprites/generator.lua",
      ["lsnes.scripts.lib.game.sprites.minorextended"] = "lsnes/scripts/lib/game/sprites/minorextended.lua",
      ["lsnes.scripts.lib.game.sprites.miscsprite"] = "lsnes/scripts/lib/game/sprites/miscsprite.lua",
      ["lsnes.scripts.lib.game.sprites.quake"] = "lsnes/scripts/lib/game/sprites/quake.lua",
      ["lsnes.scripts.lib.game.sprites.score"] = "lsnes/scripts/lib/game/sprites/score.lua",
      ["lsnes.scripts.lib.game.sprites.shooter"] = "lsnes/scripts/lib/game/sprites/shooter.lua",
      ["lsnes.scripts.lib.game.sprites.smoke"] = "lsnes/scripts/lib/game/sprites/smoke.lua",
      ["lsnes.scripts.lib.game.sprites.specialsprites"] = "lsnes/scripts/lib/game/sprites/specialsprites.lua",
      ["lsnes.scripts.lib.game.sprites.sprite"] = "lsnes/scripts/lib/game/sprites/sprite.lua",
      ["lsnes.scripts.lib.game.sprites.spritedata"] = "lsnes/scripts/lib/game/sprites/spritedata.lua",
      ["lsnes.scripts.lib.game.sprites.spriteimages"] = "lsnes/scripts/lib/game/sprites/spriteimages.lua",
      ["lsnes.scripts.lib.game.sprites.spriteinfo"] = "lsnes/scripts/lib/game/sprites/spriteinfo.lua",
      ["lsnes.scripts.lib.game.sprites.yoshi"] = "lsnes/scripts/lib/game/sprites/yoshi.lua",
      ["lsnes.scripts.lib.game.state"] = "lsnes/scripts/lib/game/state.lua",
      ["lsnes.scripts.lib.game.tile"] = "lsnes/scripts/lib/game/tile.lua",
      ["lsnes.scripts.lib.ghost"] = "lsnes/scripts/lib/ghost.lua",
      ["lsnes.scripts.lib.ibind"] = "lsnes/scripts/lib/ibind.lua",
      ["lsnes.scripts.lib.joypad"] = "lsnes/scripts/lib/joypad.lua",
      ["lsnes.scripts.lib.json"] = "lsnes/scripts/lib/json.lua",
      ["lsnes.scripts.lib.keyinput"] = "lsnes/scripts/lib/keyinput.lua",
      ["lsnes.scripts.lib.lagmeter"] = "lsnes/scripts/lib/lagmeter.lua",
      ["lsnes.scripts.lib.lsnes"] = "lsnes/scripts/lib/lsnes.lua",
      ["lsnes.scripts.lib.luap"] = "lsnes/scripts/lib/luap.lua",
      ["lsnes.scripts.lib.menu"] = "lsnes/scripts/lib/menu.lua",
      ["lsnes.scripts.lib.movieinfo"] = "lsnes/scripts/lib/movieinfo.lua",
      ["lsnes.scripts.lib.onclick"] = "lsnes/scripts/lib/onclick.lua",
      ["lsnes.scripts.lib.read"] = "lsnes/scripts/lib/read.lua",
      ["lsnes.scripts.lib.timer"] = "lsnes/scripts/lib/timer.lua",
      ["lsnes.scripts.lib.widget"] = "lsnes/scripts/lib/widget.lua",
      ["lsnes.scripts.lsnes-smw-record-ghost"] = "lsnes/scripts/lsnes-smw-record-ghost.lua",
      ["lsnes.scripts.smw-lsnes"] = "lsnes/scripts/smw-lsnes.lua",
      ["smw-tas"] = "smw-tas.lua",
      ["snes9x.scripts.lib.config"] = "snes9x/scripts/lib/config.lua",
      ["snes9x.scripts.lib.draw"] = "snes9x/scripts/lib/draw.lua",
      ["snes9x.scripts.lib.json"] = "snes9x/scripts/lib/json.lua",
      ["snes9x.scripts.lib.luap"] = "snes9x/scripts/lib/luap.lua",
      ["snes9x.scripts.lib.smw"] = "snes9x/scripts/lib/smw.lua",
      ["snes9x.scripts.smw-snes9x"] = "snes9x/scripts/smw-snes9x.lua",
      ["snes9x.scripts.snes9x-smw-record-ghost"] = "snes9x/scripts/snes9x-smw-record-ghost.lua"
   }
}
